theme: jekyll-theme-cayman
title: [ReorientDiff: Diffusion Model based Reorientation for Object Manipulation]
description: [Diffusion Models for language-conditioned multi-step object manipulation for precise object placement.]
