theme: jekyll-theme-cayman
title: [ReorientDiff: Diffusion Models for Reorientation and Regrasping]
description: [Diffusion Models for language-conditioned multi-step object manipulation for precise object placement.]
